import stud.helpler.Name;
import stud.helpler.Address;
import stud.Student;
import java.io.*;
import java.net.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.JPopupMenu.Separator;

import java.awt.*;
public class APP {
    private JFrame mainFrame;
    private JPanel entry,result,log;
    private JButton entryButton,resultButton,clearButton,submitButton;
    private JMenuBar menuBar;
    private JLabel LRegister,LFName,LMName,LLName,LGender,LContact,LFFName,LMFName,LLFName,LFMName,LMMName,LLMName,LLocation,LCity,LDistrict,LState,LCountry,LZipCode;
    private JTextField TRegister, TFName,TMName,TLName,TContact,TFFName,TMFName,TLFName,TFMName,TMMName,TLMName,TLocation,TCity,TDistrict,TState,TCountry,TZipCode;
    private JRadioButton RMale,RFemale;
    private ButtonGroup GGender;
    private JScrollPane scrollPane;

    public APP()throws Exception {
        scrollPane = new JScrollPane();
        mainFrame = new JFrame("Student Management System");
        menuBar = new JMenuBar();
        menuBar.setBackground(Color.GRAY);
        menuBar.setLayout(new FlowLayout(FlowLayout.CENTER));
        menuBar.setSize(500,40);
        entry = new JPanel();
        entry.setVisible(true);
        entry.setBounds(0, 40, 500, 500);
        entry.setBackground(Color.YELLOW);
        this.initEntryPanel();
        log = new JPanel();
        log.setName("log");
        log.setBounds(0,400,500,150);
        log.setBackground(Color.GRAY);
        log.setVisible(true);
        entryButton = new JButton("Entry");
        entryButton.setSize(250,50);
        resultButton = new JButton("Result");
        resultButton.setSize(250, 50);
        menuBar.add(entryButton);
        menuBar.add(resultButton);
        // mainFrame.add(menuBar);
        // mainFrame.add(entry);
        scrollPane.add(entry);
        mainFrame.add(scrollPane);
        scrollPane.setSize(400,400);
        // mainFrame.add(log);
        mainFrame.setLayout(new BorderLayout());
        mainFrame.setSize(500, 500);
        mainFrame.setBackground(Color.CYAN);
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        mainFrame.setVisible(true);
    }
    void initEntryPanel()throws Exception{
        LRegister = new JLabel("Register Number");
        LRegister.setBounds(10,10,200,20);
        LFName = new JLabel("First Name");
        LFName.setBounds(10,30,200,20);
        LMName = new JLabel("Middle Name");
        LMName.setBounds(10,50,200,20);
        LLName = new JLabel("Last Name");
        LLName.setBounds(10,70,200,20);
        LGender = new JLabel("Gender");
        LGender.setBounds(10,90,200,20);
        LContact = new JLabel("Phone Number");
        LContact.setBounds(10,110,200,20);
        LFFName = new JLabel("Father First Name");
        LFFName.setBounds(10,130,200,20);
        LMFName = new JLabel("Father Middle Name ");
        LMFName.setBounds(10,150,200,20);
        LLFName = new JLabel("Father Last Name");
        LLFName.setBounds(10,170,200,20);
        LFMName = new JLabel("Mother First Name");
        LFMName.setBounds(10,190,200,20);
        LMMName = new JLabel("Mother Middle Name");
        LMMName.setBounds(10,210,200,20);
        LLMName = new JLabel("Mother Last Name");
        LLMName.setBounds(10,230,200,20);
        LLocation = new JLabel("House/Flat No.");
        LLocation.setBounds(10,250,200,20);
        LCity = new JLabel("City");
        LCity.setBounds(10,270,200,20);
        LDistrict = new JLabel("District");
        LDistrict.setBounds(10,290,200,20);
        LState = new JLabel("State");
        LState.setBounds(10,310,200,20);
        LCountry = new JLabel("Country");
        LCountry.setBounds(10,330,200,20);
        LZipCode = new JLabel("ZipCode");
        LZipCode.setBounds(10,350,200,20);
        TRegister = new JTextField(15);
        TRegister.setBounds(200,10,200,20);
        TFName = new JTextField(30);
        TFName.setBounds(200,30,200,20);
        TMName = new JTextField(30);
        TMName.setBounds(200,50,200,20);
        TLName = new JTextField(30);
        TLName.setBounds(200,70,200,20);
        RMale = new JRadioButton("Male");
        RMale.setBounds(200,90,200,20);
        RFemale = new JRadioButton("Female");
        RFemale.setBounds(400,90,200,20);
        GGender = new ButtonGroup();
        GGender.add(RMale);
        GGender.add(RFemale);
        TContact = new JTextField(15);
        TContact.setBounds(200,110,200,20);
        TFFName = new JTextField(30);
        TFFName.setBounds(200,130,200,20);
        TMFName =new JTextField(30);
        TMFName.setBounds(200,150,200,20);
        TLFName = new JTextField(30);
        TLFName.setBounds(200,170,200,20);
        TFMName = new JTextField(30);
        TFMName.setBounds(200,190,200,20);
        TMMName = new JTextField(30);
        TMMName.setBounds(200,210,200,20);
        TLMName = new JTextField(30);
        TLMName.setBounds(200,230,200,20);
        TLocation = new JTextField(50);
        TLocation.setBounds(200,250,200,20);
        TCity = new JTextField(30);
        TCity.setBounds(200,270,200,20);
        TDistrict = new JTextField(30);
        TDistrict.setBounds(200,290,200,20);
        TState = new JTextField(30);
        TState.setBounds(200,310,200,20);
        TCountry = new JTextField(30);
        TCountry.setBounds(200,330,200,20);
        TZipCode = new JTextField(6);
        TZipCode.setBounds(200,350,200,20);
        

        clearButton = new JButton("Clear");
        clearButton.setBounds(200 ,375,100,55);
        submitButton = new JButton("Submit");
        submitButton.setBounds(400,375,100,55);
        entry.add(LRegister);
        entry.add(TRegister);
        entry.add(LFName);
        entry.add(TFName);
        entry.add(LMName);
        entry.add(TMName);
        entry.add(LLName);
        entry.add(TLName);
        entry.add(LGender);
        entry.add(RMale);
        entry.add(RFemale);
        entry.add(LContact);
        entry.add(TContact);
        entry.add(LFFName);
        entry.add(TFFName);
        entry.add(LMFName);
        entry.add(TMFName);
        entry.add(LLFName);
        entry.add(TLFName);
        entry.add(LFMName);
        entry.add(TFMName);
        entry.add(LMMName);
        entry.add(TMMName);
        entry.add(LLMName);
        entry.add(TLMName);
        entry.add(LLocation);
        entry.add(TLocation);
        entry.add(LCity);
        entry.add(TCity);
        entry.add(LDistrict);
        entry.add(TDistrict);
        entry.add(LState);
        entry.add(TState);
        entry.add(LCountry);
        entry.add(TCountry);
        entry.add(LZipCode);
        entry.add(TZipCode);
        entry.add(clearButton);
        entry.add(submitButton);
        entry.setLayout(new BorderLayout());
    }
    public void setupResultPanel(){
        
    }
    public static void main(String[] args) throws Exception {
        APP mainApp = new APP();
        // mainApp.initEntryPanel();
    }
    
}
